<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SupperBackEnd.Dto\SupperBackEnd.Dto.csproj" />
    <ProjectReference Include="..\CartService.DAL\CartService.DAL.csproj" />
    <ProjectReference Include="..\CartService.Domain\CartService.Domain.csproj" />
  </ItemGroup>

</Project>
