<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Properties\secretsSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Properties\secretsSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductService\ClusterService\BLL\BLL.csproj" />
    <ProjectReference Include="..\ProductService\ClusterService\DAL\DAL.csproj" />
    <ProjectReference Include="..\ProductService\ClusterService\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
