syntax = "proto3";

option csharp_namespace = "GrpcAPI";

package greet;

// The greeting service definition.
service Identity {
	rpc GetGuestToken (GuestTokenRequest) returns (TokenReply);
	rpc CreateUser (CreateUserRequest) returns (TokenReply);
	rpc AuthUser (AuthUserRequest) returns (TokenReply);
	rpc PromoteUser (PromoteUserRequest) returns (PromoteUserReply);
	rpc GetUserSelfInfoByToken (GetUserSelfInfoByTokenRequest) returns (GetUserSelfInfoReply);
	rpc GetUserSelfInfoById (GetUserSelfInfoByIdRequest) returns (GetUserSelfInfoReply);
	rpc ValidateToken (ValidateTokenRequest) returns (ValidateTokenReply);
}

// Requests
message GuestTokenRequest {
	string deviceName = 2;
	string deviceIp = 3;
}
message CreateUserRequest {
	string token = 1;
	string username = 2;
	string password = 3;
}
message ChangePasswordRequest {
	string token = 1;
	string currentPassword = 2;
	string newPassword = 3;
}
message AuthUserRequest {
	string username = 1;
	string password = 2;
	string deviceName = 3;
	string deviceIp = 4;
}
message PromoteUserRequest {
	string token = 1;
	int32 shopId = 2;
	bool isHost = 3;
}
message GetUserSelfInfoByTokenRequest {
	string token = 1;
}
message GetUserSelfInfoByIdRequest {
	int32 id = 1;
}
message ValidateTokenRequest {
	string token = 1;
}
// Replies
message TokenReply {
	string token = 1;
}
message PromoteUserReply {
	bool isPromoted = 1;
	string newToken = 2;
}
message GetUserSelfInfoReply{
	int32 id = 1;
	string name = 2;
	string email = 3;
	string phone = 4;
	int32 telegramId = 5;
	bool isDeleted = 6;
}
message ValidateTokenReply{
	bool isValid = 1;
}
